### PR TITLE
Order display bug

### PR DESCRIPTION
**Pull request by Garabed96**
https://www.notion.so/hamza-market-token/Empty-Orders-Page-2c3b1cbfb3ca44989a437eec40df9d32?pvs=4

Cleanup for showing empty page

### CODE REVIEW

**Comment by Garabed96** [comment]
don't merge theres a bug I noticed on second round of testing

**Comment by Garabed96** [comment]
ok this is ready to merge

**Comment by Garabed96** [comment]
another bug dont merge please

**Comment by Garabed96** [comment]
working fine now

**Review by jrkosinski — APPROVED** [review]

**Pull request merged**
